name: helmholtz-solver
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - numpy=1.26.3
  - pandas=2.2.0
  - matplotlib=3.8.2
  - seaborn=0.13.2
  - gmsh=4.12.2
  - h5py=3.10.0
  - conda-forge::fenics-dolfinx=0.7.2
  - black=23.12.1
  - ruff=0.1.14
  - isort=5.13.2
  - pre-commit=3.6.0
  - pytest=7.4.4
  - pytest-cov=4.1.0
  - sphinx